name: Periodic health check

on:
  schedule:
    - cron: '0 0 1 * *'     # at midnight on the first day of every month 
jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://shrouded-taiga-81794.herokuapp.com/health